package com.softtek.acceleo.demo.domain;

public enum AuthorityName {
	
ROLE_MODULECREATE, ROLE_MODULESEARCH, ROLE_MODULEUPDATE, ROLE_MODULEDELETE, 
ROLE_MENUCREATE, ROLE_MENUSEARCH, ROLE_MENUUPDATE, ROLE_MENUDELETE, 
ROLE_FUNCTIONALSERVICECREATE, ROLE_FUNCTIONALSERVICESEARCH, ROLE_FUNCTIONALSERVICEUPDATE, ROLE_FUNCTIONALSERVICEDELETE, 
ROLE_APPLICATIONCREATE, ROLE_APPLICATIONSEARCH, ROLE_APPLICATIONUPDATE, ROLE_APPLICATIONDELETE, 
ROLE_USER, ROLE_ADMIN, ROLE_ANONYMOUS

}
