package com.softtek.acceleo.demo.domain;

public enum AuthorityName {
	
ROLE_ETIQUETAASIGNADACREATE, ROLE_ETIQUETAASIGNADASEARCH, ROLE_ETIQUETAASIGNADAUPDATE, ROLE_ETIQUETAASIGNADADELETE, 
ROLE_CLIENTECREATE, ROLE_CLIENTESEARCH, ROLE_CLIENTEUPDATE, ROLE_CLIENTEDELETE, 
ROLE_ORDENSIMPLIFICADACREATE, ROLE_ORDENSIMPLIFICADASEARCH, ROLE_ORDENSIMPLIFICADAUPDATE, ROLE_ORDENSIMPLIFICADADELETE, 
ROLE_OPERADORPRODUCCIONCREATE, ROLE_OPERADORPRODUCCIONSEARCH, ROLE_OPERADORPRODUCCIONUPDATE, ROLE_OPERADORPRODUCCIONDELETE, 
ROLE_USER, ROLE_ADMIN, ROLE_ANONYMOUS

}
